// Angular/src/app/intro/components/navbar/navbar.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent implements OnInit {
  @Input() hoverBg: boolean;

  constructor() { }

  ngOnInit(): void {
  }

  @Input() handleHover: void;
  
}

<div className="intro-nav">
  <ul className="menu">
    <Link
      onMouseEnter={handleHover}
      onMouseLeave={handleHover}
      to="/"
      className="sing-up"
    >
      SING UP
    </Link>
    <Link
      onMouseEnter={handleHover}
      onMouseLeave={handleHover}
      to="home"
      className={hoverBg ? "sing-in hoveredBtn" : "sing-in"}
    >
      SING IN
    </Link>
  </ul>
</div>

// React/src/pages/Login/components/Navbar/index.tsx
import React from "react";

import "./styles.css";
import { Link } from "react-router-dom";

interface navBarProps {
  handleHover: any;
  hoverBg: boolean;
}

export default function Navbar({ handleHover, hoverBg }: navBarProps) {
  return (
    <div className="login-nav">
      <ul className="menu">
        <Link
          onMouseEnter={handleHover}
          onMouseLeave={handleHover}
          to="/"
          className={hoverBg ? "go-back" : "go-back"}
        >
          <i className="fas fa-arrow-left"></i>
        </Link>
        <Link
          onMouseEnter={handleHover}
          onMouseLeave={handleHover}
          to="register"
          className={hoverBg ? "sing-in hoveredBTn" : "sing-in"}
        >
          SING UP
        </Link>
      </ul>
    </div>
  );
}
