// React/src/pages/Home/components/Todo/index.tsx
import React from "react";

import './styles.css';

interface todoProps {
  text: string,
  completed: boolean,
  id: any,
  todos: any,
  setTodos: any,
}

const Todo = ({text, completed, id, todos, setTodos} : todoProps) => {

  const handleDelete = () => {
    setTodos(todos.filter((el : any) => el.id !== id));
  }
  const handleComplete = () => {
    setTodos(todos.map((item : any) => {
      if(item.id === id) {
        return {
          ...item, completed: !item.completed
        }
      }
      return item;
    }));
  }

  return (
      <div id={id} className={completed ? "todo completed" : "todo"}>
        <li className="todo-item">{text}</li>
        <button onClick={handleComplete} className={completed ? "complete-btn uncomplete-btn": "complete-btn"}>
          <i className="fas fa-check"></i>
        </button>
        <button onClick={handleDelete} className="trash-btn">
          <i className="fas fa-trash"></i>
        </button>
      </div>
  );
};

export default Todo;

// Angular/src/app/home/todo/todo.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.scss']
})
export class TodoComponent implements OnInit {
  @Output() delete = new EventEmitter();
  @Output() complete = new EventEmitter();
  @Input() id: number; 
  @Input() text: string; 
  @Input() completed: boolean; 

  constructor() { }

  ngOnInit(): void {
  }

}

<div id="{{id}}" class="{{completed ? 'todo completed' : 'todo'}}">
  <li class="todo-item">{{text}}</li>
  <button (click)="complete.emit(id)" class="{{completed ? 'complete-btn uncomplete-btn': 'complete-btn'}}">
    <i class="fas fa-check"></i>
  </button>
  <button (click)="delete.emit(id)" class="trash-btn">
    <i class="fas fa-trash"></i>
  </button>
</div>
