// Angular/src/app/home/todo-maker/todo-maker.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';

interface Todo {
  userId: number;
  id: number;
  title: string;
  completed: boolean;
}

@Component({
  selector: 'app-todo-maker',
  templateUrl: './todo-maker.component.html',
  styleUrls: ['./todo-maker.component.scss']
})
export class TodoMakerComponent implements OnInit {
  inputText: string = 'hehehe';
  @Output() submit = new EventEmitter()

  constructor() { }

  ngOnInit(): void {
  }

  inputTextHandler(txt: string) {
    this.inputText = txt;
  }
  handleSubmit(e: Event) {
    e.preventDefault();

    const newTodo: Todo = {
      userId: Math.random(),
      id: Math.random() * 12,
      title: this.inputText,
      completed: false
    }

    // SEND UP TO PARENT
    this.submit.emit(newTodo);
    // CLEAR INPUT
    e.srcElement[0].value = "";
  }
}

<div class="todo-maker">
  <p>What can't you forget to do today?</p>
  <form (submit)="handleSubmit($event)">
    <div class="todoInput">
      <input
        #inpTxt
        (change)="inputTextHandler(inpTxt.value)"
        type="text"
        class="todo-input"
        placeholder="Complete my todos"
        required
      />
      <button class="todo-button" type="submit">
        <i class="fas fa-plus-square"></i>
      </button>
    </div>
  </form>
</div>

// React/src/pages/Home/components/TodoMaker/index.tsx
import React, { FormEvent, ChangeEvent } from 'react';

import './styles.css';

interface todoMakerProps {
  setInputText: any;
  setTodos: any;
  todos: any;
  inputText: string
}

const TodoMaker = ({setInputText, setTodos, todos, inputText} : todoMakerProps) => {
  
  const inputTextHandler = (e: ChangeEvent) => {
    const input = e.target as HTMLTextAreaElement;
    setInputText(input.value); 
  }

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    setTodos([
      ...todos, {text: inputText, completed: false, id: Math.random() * 1000 }
    ]);
    setInputText('');
  }
  
  return (
    <div className="todo-maker">
        <p>What can't you forget to do today?</p>
        <form onSubmit={handleSubmit}>
          <div className="todoInput">
            <input 
              value={inputText} 
              onChange={inputTextHandler} 
              type="text" 
              className="todo-input" 
              placeholder="Complete my todos" 
              required
            />
            <button className="todo-button" type="submit">
              <i className="fas fa-plus-square"></i>
            </button>
          </div>
        </form>
    </div>
  );
}

export default TodoMaker;
